package com.sc3.somewear.sdk

import android.net.Uri

/** Low-level IPC contract implemented by the separately installed gateway APK. */
public object SomewearGatewayContract {
    public const val DEFAULT_PACKAGE: String = "com.somewearlabs.swtak.plugin"
    public const val DEFAULT_AUTHORITY: String =
        "com.somewearlabs.swtak.plugin.somewear.gateway"
    public const val WORKSPACE_QR_SCANNER_ACTIVITY: String =
        "com.somewearlabs.gateway.WorkspaceQrScannerActivity"
    public const val GATEWAY_SERVICE: String =
        "com.somewearlabs.gateway.SomewearGatewayService"
    public const val PERMISSION: String =
        "com.somewearlabs.swtak.plugin.permission.SOMEWEAR_GATEWAY"

    @JvmField
    public val DEFAULT_URI: Uri = Uri.parse("content://$DEFAULT_AUTHORITY")

    public object Method {
        public const val INFO: String = "info"
        public const val INITIALIZE: String = "activate"
        public const val CONNECT_BLUETOOTH: String = "connectBle"
        public const val CONNECT_USB: String = "connectUsb"
        public const val GET_DEVICE_STATUS: String = "getDeviceStatus"
        public const val GET_NODE_TELEMETRY: String = "getNodeTelemetry"
        public const val GET_MESH_NETWORK_STATUS: String = "getMeshNetworkStatus"
        public const val CANCEL_CONNECTION: String = "cancelConnection"
        public const val SET_CONNECTION_MODE: String = "setConnectionMode"
        public const val DISCONNECT: String = "disconnect"
        public const val SHUTDOWN: String = "shutdown"
        public const val POWER_ON: String = "powerOn"
        public const val POWER_OFF: String = "powerOff"
        public const val GET_HARDWARE_SETTINGS: String = "getHardwareSettings"
        public const val SET_TRACKING_ENABLED: String = "setTrackingEnabled"
        public const val SET_TRACKING_INTERVAL: String = "setTrackingInterval"
        public const val SET_BACKHAUL_ENABLED: String = "setBackhaulEnabled"
        public const val SET_SATELLITE_ENABLED: String = "setSatelliteEnabled"
        public const val SET_MESH_RADIO_ENABLED: String = "setMeshRadioEnabled"
        public const val SET_RADIO_CHANNEL: String = "setRadioChannel"
        public const val SET_MESH_TRANSMISSION_STRENGTH: String =
            "setMeshTransmissionStrength"
        public const val SET_LED_LIGHT_ENABLED: String = "setLedLightEnabled"
        public const val SET_VIBRATION_FEEDBACK_ENABLED: String =
            "setVibrationFeedbackEnabled"
        public const val SET_ENDURANCE_MODE_ENABLED: String = "setEnduranceModeEnabled"
        public const val SET_DEVICE_BUTTON_FUNCTION: String = "setDeviceButtonFunction"
        public const val FACTORY_RESET: String = "factoryReset"
        public const val SEND_MESSAGE_V2: String = "sendMessageV2"
        public const val CANCEL_MESSAGE: String = "cancelMessage"
        public const val GET_DELIVERY_STATUS: String = "getDeliveryStatus"
        public const val POLL_INCOMING_MESSAGES: String = "pollIncomingMessages"
        internal const val PREPARE_FILE_UPLOAD: String = "prepareFileUpload"
        internal const val SEND_FILE_METADATA: String = "sendFileMetadata"
        public const val POLL_INCOMING_FILES: String = "pollIncomingFiles"
        internal const val GET_FILE_DOWNLOAD_URL: String = "getFileDownloadUrl"
        public const val GET_RECEIVE_HEALTH: String = "getReceiveHealth"
        internal const val START_RECEIVING: String = "startReceiving"
        public const val JOIN_WORKSPACE: String = "joinWorkspace"
        public const val SYNC_WORKSPACES: String = "syncWorkspaces"
        public const val GET_WORKSPACE_PROVISIONING_STATUS: String =
            "getWorkspaceProvisioningStatus"
        public const val LIST_WORKSPACES: String = "listWorkspaces"
        public const val GET_ACTIVE_WORKSPACE: String = "getActiveWorkspace"
        public const val ACTIVATE_WORKSPACE: String = "activateWorkspace"
        public const val GET_WORKSPACE_STATUS: String = "getWorkspaceStatus"
        public const val GET_MESH_KEY_STATUS: String = "getMeshKeyStatus"
    }

    public object Key {
        public const val OK: String = "ok"
        public const val MESSAGE: String = "message"
        public const val ERROR_CODE: String = "error_code"
        public const val API_VERSION: String = "api_version"
        public const val CAPABILITIES: String = "capabilities"

        public const val ADDRESS: String = "address"
        public const val CONNECTION_STATE: String = "connection_state"
        public const val OPERATION_STATE: String = "operation_state"
        public const val OPERATION_RESULT: String = "operation_result"
        public const val LOCAL_TRANSPORT: String = "local_transport"
        public const val CONNECTION_MODE: String = "connection_mode"
        public const val ENABLED: String = "enabled"
        public const val TRACKING_ENABLED: String = "tracking_enabled"
        public const val TRACKING_GPS_SECONDS: String = "tracking_gps_seconds"
        public const val TRACKING_SENDING_SECONDS: String = "tracking_sending_seconds"
        public const val BACKHAUL_ENABLED: String = "backhaul_enabled"
        public const val SATELLITE_ENABLED: String = "satellite_enabled"
        public const val MESH_RADIO_ENABLED: String = "mesh_radio_enabled"
        public const val LOW_SPEED_FREQUENCY_HZ: String = "low_speed_frequency_hz"
        public const val HIGH_SPEED_FREQUENCY_HZ: String = "high_speed_frequency_hz"
        public const val MESH_TRANSMISSION_STRENGTH: String =
            "mesh_transmission_strength"
        public const val LED_LIGHT_ENABLED: String = "led_light_enabled"
        public const val VIBRATION_FEEDBACK_ENABLED: String = "vibration_feedback_enabled"
        public const val ENDURANCE_MODE_ENABLED: String = "endurance_mode_enabled"
        public const val DEVICE_BUTTON_FUNCTION: String = "device_button_function"
        public const val FACTORY_RESET_CONFIRMATION: String = "factory_reset_confirmation"

        public const val BATTERY_PERCENT: String = "battery_percent"
        public const val CHARGE_STATUS: String = "charge_status"
        public const val POWER_STATUS: String = "power_status"
        public const val ACTIVITY_STATE: String = "activity_state"
        public const val SATELLITE_QUALITY: String = "satellite_quality"
        public const val SATELLITE_SENDABLE: String = "satellite_sendable"
        public const val FIRMWARE_VERSION: String = "firmware_version"
        public const val NETWORK_VERSION: String = "network_version"
        public const val HARDWARE_FLAVOR: String = "hardware_flavor"
        public const val SERIAL_NUMBER: String = "serial_number"
        public const val IMEI: String = "imei"
        public const val GPS_INITIAL_FIX: String = "gps_initial_fix"
        public const val TRACKING_STATE: String = "tracking_state"
        public const val LOW_BANDWIDTH_MULTIPLIER: String = "low_bandwidth_multiplier"
        public const val WAKE_AT_MS: String = "wake_at_ms"
        public const val SAMPLED_AT_MS: String = "sampled_at_ms"

        public const val MESH_AVAILABLE: String = "mesh_available"
        public const val MESH_PEER_USER_ID: String = "mesh_peer_user_id"
        public const val MESH_NEXT_HOP_USER_ID: String = "mesh_next_hop_user_id"
        public const val MESH_HOPS: String = "mesh_hops"
        public const val MESH_RSSI: String = "mesh_rssi"
        public const val MESH_CAN_BACKHAUL: String = "mesh_can_backhaul"
        public const val MESH_UPDATED_AT_MS: String = "mesh_updated_at_ms"

        public const val MESSAGE_ID: String = "message_id"
        public const val CONTENT: String = "message"
        public const val WORKSPACE_ID: String = "workspace_id"
        public const val TARGET_USER_ID: String = "target_user_id"
        public const val ROUTE_POLICY: String = "route_policy"
        public const val RADIO_TIMEOUT_MS: String = "radio_timeout_ms"
        public const val SATELLITE_TIMEOUT_MS: String = "satellite_timeout_ms"
        public const val PARCEL_ID: String = "parcel_id"
        public const val FRAGMENT_COUNT: String = "fragment_count"
        public const val RADIO_FRAGMENTED: String = "radio_fragmented"
        public const val SATELLITE_FALLBACK_ARMED: String = "satellite_fallback_armed"
        public const val ACCEPTED_AT_MS: String = "accepted_at_ms"

        internal const val FILE_UPLOAD_URL: String = "file_upload_url"
        public const val FILE_ID: String = "file_id"
        public const val FILE_NAME: String = "file_name"
        public const val MIME_TYPE: String = "mime_type"
        public const val FILE_SIZE_BYTES: String = "file_size_bytes"
        internal const val FILE_SHA256: String = "file_sha256"
        public const val FILE_USER_ID: String = "file_user_id"
        public const val FILE_CREATED_AT_MS: String = "file_created_at_ms"
        public const val FILE_UPLOADED_AT_MS: String = "file_uploaded_at_ms"
        internal const val FILE_DOWNLOAD_URL: String = "file_download_url"

        public const val DELIVERY_STATUS: String = "delivery_status"
        public const val DELIVERED_CHANNEL: String = "delivered_channel"
        public const val ERROR_REASON: String = "error_reason"
        public const val UPDATED_AT_MS: String = "updated_at_ms"

        public const val AFTER_SEQUENCE: String = "after_sequence"
        public const val LIMIT: String = "limit"
        public const val ITEMS: String = "items"
        public const val SEQUENCE: String = "sequence"
        public const val SENDER_ID: String = "sender_id"
        public const val RECEIVED_AT_MS: String = "received_at_ms"
        public const val RECEIVE_SUBSCRIPTION_ACTIVE: String = "receive_subscription_active"
        public const val ROUTER_CALLBACK_COUNT: String = "router_callback_count"
        public const val INBOUND_MESSAGE_COUNT: String = "inbound_message_count"
        public const val IGNORED_INBOUND_COUNT: String = "ignored_inbound_count"
        public const val RECEIVE_ERROR_COUNT: String = "receive_error_count"
        public const val LAST_ROUTER_CALLBACK_AT_MS: String = "last_router_callback_at_ms"
        public const val LAST_INBOUND_MESSAGE_AT_MS: String = "last_inbound_message_at_ms"
        public const val LAST_RECEIVE_ERROR_AT_MS: String = "last_receive_error_at_ms"
        public const val LAST_PAYLOAD_TYPE: String = "last_payload_type"
        public const val LAST_RECEIVE_ERROR: String = "last_receive_error"
        public const val QUEUED_INCOMING_COUNT: String = "queued_incoming_count"
        public const val LATEST_SEQUENCE: String = "latest_sequence"

        public const val INVITE_CODE: String = "invite_code"
        public const val WORKSPACE_TIMEOUT_MS: String = "workspace_timeout_ms"
        public const val WORKSPACE_SYNC_COMPLETED: String = "workspace_sync_completed"
        public const val WORKSPACE_NAME: String = "workspace_name"
        public const val WORKSPACE_READY: String = "workspace_ready"
        public const val WORKSPACE_ACTIVE: String = "workspace_active"
        public const val WORKSPACE_MEMBER: String = "workspace_member"
        public const val HAS_ACTIVE_WORKSPACE: String = "has_active_workspace"
        public const val WORKSPACES: String = "workspaces"
        public const val MESH_KEY_INSTALLED: String = "mesh_key_installed"
        public const val MESH_KEY_ID: String = "mesh_key_id"
        public const val AUTHENTICATED: String = "authenticated"
        public const val AUTH_STATE: String = "auth_state"
        public const val WORKSPACE_COUNT: String = "workspace_count"
    }
}
